apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: forgestudio-prod
data:
  nginx.conf: |
    events {}

    http {

      ########################################
      # COMMON PROXY SETTINGS
      ########################################
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;

      ########################################
      # FORGESPHERE
      ########################################
      server {
        listen 80;
        server_name forgesphere.probestack.io;

        location /api-design/ {
          proxy_pass http://fsp-api-design-svc.forgesphere-prod.svc.cluster.local;
        }

        location /api-development/ {
          proxy_pass http://fsp-api-development-svc.forgesphere-prod.svc.cluster.local;
        }

        location /mock-api/ {
          proxy_pass http://fsp-api-mock-svc.forgesphere-prod.svc.cluster.local;
        }

        location /consumer/ {
          proxy_pass http://fsp-consumer-svc.forgesphere-prod.svc.cluster.local;
        }

        location /contract-testing/ {
          proxy_pass http://fsp-contract-testing-svc.forgesphere-prod.svc.cluster.local;
        }

        location /onboarding/ {
          proxy_pass http://fsp-onboarding-svc.forgesphere-prod.svc.cluster.local;
        }

        location /gatewayonboarding/ {
          proxy_pass http://fsp-gatewayonboarding-svc.forgesphere-prod.svc.cluster.local;
        }

        location /compliance-api/ {
          proxy_pass http://fsp-compliance-svc.forgesphere-prod.svc.cluster.local;
        }

        location /provider/ {
          proxy_pass http://fsp-provider-api-svc.forgesphere-prod.svc.cluster.local;
        }

        location /requirement/ {
          proxy_pass http://fsp-requirement-mgmt-svc.forgesphere-prod.svc.cluster.local;
        }

        location /test/ {
          proxy_pass http://fsp-test-generation-svc.forgesphere-prod.svc.cluster.local;
        }

        location /kong-wrapper/ {
          proxy_pass http://fsp-kong-wrapper-svc.forgesphere-prod.svc.cluster.local;
        }

        location /mcp-generate/v1/api/ {
          proxy_pass http://fsp-mcp-generation-svc.forgesphere-prod.svc.cluster.local;
        }

        location /apigee-wrapper/ {
            proxy_pass http://fsp-apigee-wrapper-svc.forgesphere-prod.svc.cluster.local/apigee-wrapper/;
        }

        location / {
          proxy_pass http://forgesphere-fe.forgesphere-prod.svc.cluster.local;
        }
      }

      ########################################
      # FORGEHUB
      ########################################
      server {
        listen 80;
        server_name prod.forgehub.probestack.io;

        location / {
          proxy_pass http://forgehub-fe.forgehub-prod.svc.cluster.local;
        }
      }

      ########################################
      # FORGEAI
      ########################################
      server {
        listen 80;
        server_name forgeai.probestack.io;

        location / {
          proxy_pass http://forgeai-fe.forgeai-prod.svc.cluster.local;
        }
      }

      ########################################
      # FORGEKONNECT
      ########################################
      server {
        listen 80;
        server_name forgekonnect.probestack.io;

        location / {
          proxy_pass http://forgekonnect-fe.forgekonnect-prod.svc.cluster.local;
        }
      }
    }